-- Import final batch of Swedish golf clubs
INSERT INTO public.golf_courses (name, location, image, latitude, longitude) VALUES
-- Final remaining clubs
('Skepparslövs Golfklubb', 'Skepparslöv', '/placeholder.svg', 0, 0),
('Alstermo Golfklubb', 'Alstermo', '/placeholder.svg', 0, 0),
('Anderstorp Golfklubb', 'Anderstorp', '/placeholder.svg', 0, 0),
('Backagårdens Golfklubb', 'Borlänge', '/placeholder.svg', 0, 0),
('Backtorp Golfklubb', 'Enköping', '/placeholder.svg', 0, 0),
('Ballingslövs Golfklubb', 'Bjuv', '/placeholder.svg', 0, 0),
('Bara Golfklubb', 'Bara', '/placeholder.svg', 0, 0),
('Bedinge Golfklubb', 'Bedinge', '/placeholder.svg', 0, 0),
('Berga Golfklubb', 'Berga', '/placeholder.svg', 0, 0),
('Bergsjöns Golfklubb', 'Göteborg', '/placeholder.svg', 0, 0),
('Bjäre Golfklubb', 'Båstad', '/placeholder.svg', 0, 0),
('Bjärnum Golf Club', 'Bjärnum', '/placeholder.svg', 0, 0),
('Blackstone Golf Club', 'Boden', '/placeholder.svg', 0, 0),
('Blekinge Golfklubb', 'Karlskrona', '/placeholder.svg', 0, 0),
('Bokskogen Golf Resort', 'Bro', '/placeholder.svg', 0, 0),
('Bollebygds Golfklubb', 'Bollebygd', '/placeholder.svg', 0, 0),
('Bommersvik Golfklubb', 'Bommersvik', '/placeholder.svg', 0, 0),
('Brastad Golfklubb', 'Brastad', '/placeholder.svg', 0, 0),
('Bromölla Golfklubb', 'Bromölla', '/placeholder.svg', 0, 0),
('Brösarps Golfklubb', 'Brösarp', '/placeholder.svg', 0, 0),
('Bunkeflostrand Golf Club', 'Malmö', '/placeholder.svg', 0, 0),
('Bysjöäng Golf Club', 'Tibro', '/placeholder.svg', 0, 0),
('Båstads Golfklubb', 'Båstad', '/placeholder.svg', 0, 0),
('Bålsta Golfklubb', 'Bålsta', '/placeholder.svg', 0, 0),
('Centrumgolf AB', 'Stockholm', '/placeholder.svg', 0, 0),
('Chalmers Golfklubb', 'Göteborg', '/placeholder.svg', 0, 0),
('Cypresspoint Golf Club', 'Göteborg', '/placeholder.svg', 0, 0),
('Dalslands Golfklubb', 'Dalsland', '/placeholder.svg', 0, 0),
('Danderyd Golf & Country Club', 'Danderyd', '/placeholder.svg', 0, 0),
('Degeberga-Widtsköfle Golfklubb', 'Degeberga', '/placeholder.svg', 0, 0),
('Driburg Golfklubb', 'Finspång', '/placeholder.svg', 0, 0),
('Ekebygårdens Golf Club', 'Skurup', '/placeholder.svg', 0, 0),
('Engelholm Golf Club', 'Ängelholm', '/placeholder.svg', 0, 0),
('Falkenberg Strandbad Golf Club', 'Falkenberg', '/placeholder.svg', 0, 0),
('Farsta Golfklubb', 'Stockholm', '/placeholder.svg', 0, 0),
('Filipstad Country Club', 'Filipstad', '/placeholder.svg', 0, 0),
('Finspångs Golfklubb', 'Finspång', '/placeholder.svg', 0, 0),
('Fladdermossens Golfklubb', 'Helsingborg', '/placeholder.svg', 0, 0),
('Ljungbyheds Golf Club', 'Ljungbyhed', '/placeholder.svg', 0, 0),
('Lungre Golf Club', 'Svenljunga', '/placeholder.svg', 0, 0),
('Lyckorna Golf Club', 'Sala', '/placeholder.svg', 0, 0),
('Malmslätts Golf Club', 'Malmslätts', '/placeholder.svg', 0, 0),
('Mantorps Golf Club', 'Mantorp', '/placeholder.svg', 0, 0),
('Mariestad Golf Club', 'Mariestad', '/placeholder.svg', 0, 0),
('Mullsjö Golf Club', 'Mullsjö', '/placeholder.svg', 0, 0),
('Mörrum Golf Club', 'Mörrum', '/placeholder.svg', 0, 0),
('Mörrums Golf & Country Club', 'Mörrum', '/placeholder.svg', 0, 0),
('Nacka Golf Club', 'Nacka', '/placeholder.svg', 0, 0),
('Norsjö Golf Club', 'Norsjö', '/placeholder.svg', 0, 0),
('Näsbyholm Golf Club', 'Näsbyholm', '/placeholder.svg', 0, 0),
('Odenskog Golf Club', 'Odenskog', '/placeholder.svg', 0, 0),
('Onsjö Golf Club', 'Onsjö', '/placeholder.svg', 0, 0),
('Orust Golf Club', 'Orust', '/placeholder.svg', 0, 0),
('Oxelösund Golf Club', 'Oxelösund', '/placeholder.svg', 0, 0),
('Parksidans Golf Club', 'Stockholm', '/placeholder.svg', 0, 0),
('Piteå Golf Club', 'Piteå', '/placeholder.svg', 0, 0),
('Ramnäs Golf Club', 'Ramnäs', '/placeholder.svg', 0, 0),
('Ranberg Golf Club', 'Töreboda', '/placeholder.svg', 0, 0),
('Ribersborg Golf Club', 'Malmö', '/placeholder.svg', 0, 0),
('Riseberga Golf Club', 'Riseberga', '/placeholder.svg', 0, 0),
('Rossöns Golf Club', 'Rossön', '/placeholder.svg', 0, 0),
('Rossö Golf Club', 'Halmstad', '/placeholder.svg', 0, 0),
('Rya Golf Club', 'Göteborg', '/placeholder.svg', 0, 0),
('Sala Golf Club', 'Sala', '/placeholder.svg', 0, 0),
('Sandefjord Golf Club', 'Vetlanda', '/placeholder.svg', 0, 0),
('Sandhamn Golf Club', 'Sandhamn', '/placeholder.svg', 0, 0),
('Sekisui Alvesta Golf Club', 'Alvesta', '/placeholder.svg', 0, 0),
('Silverdal Golf Club', 'Söderköping', '/placeholder.svg', 0, 0),
('Simlångsdalen Golf Club', 'Halmstad', '/placeholder.svg', 0, 0),
('Sjöbo Golf Club', 'Sjöbo', '/placeholder.svg', 0, 0),
('Skillinge Golf Club', 'Skillinge', '/placeholder.svg', 0, 0),
('Skyllermarks Golf Club', 'Västervik', '/placeholder.svg', 0, 0),
('Sollerö Golf Club', 'Mora', '/placeholder.svg', 0, 0),
('Stendörrens Golf Club', 'Stendörren', '/placeholder.svg', 0, 0),
('Storebro Golf Club', 'Storebro', '/placeholder.svg', 0, 0),
('Sundby Golf Club', 'Torsby', '/placeholder.svg', 0, 0),
('Sundsvall Golf Club', 'Sundsvall', '/placeholder.svg', 0, 0),
('Svalöv Golf Club', 'Svalöv', '/placeholder.svg', 0, 0),
('Säffle Golf Club', 'Säffle', '/placeholder.svg', 0, 0),
('Tanums Golf Club', 'Tanum', '/placeholder.svg', 0, 0),
('Torekov Golf Club', 'Torekov', '/placeholder.svg', 0, 0),
('Tortuna Golf Club', 'Tortuna', '/placeholder.svg', 0, 0),
('Tranås Golf Club', 'Tranås', '/placeholder.svg', 0, 0),
('Ullevi Golf Club', 'Göteborg', '/placeholder.svg', 0, 0),
('Vaxholm Golf Club', 'Vaxholm', '/placeholder.svg', 0, 0),
('Vedby Golf Club', 'Vedby', '/placeholder.svg', 0, 0),
('Vetlanda Golf Club', 'Vetlanda', '/placeholder.svg', 0, 0),
('Visby Golf Club', 'Visby', '/placeholder.svg', 0, 0),
('Vittsjö Golf Club', 'Vittsjö', '/placeholder.svg', 0, 0),
('Värmlands Golf Club', 'Karlstad', '/placeholder.svg', 0, 0),
('Wapnö Golf Club', 'Halmstad', '/placeholder.svg', 0, 0),
('Wedholms Golf Club', 'Wedholm', '/placeholder.svg', 0, 0),
('Wittsjö Golf Club', 'Wittsjö', '/placeholder.svg', 0, 0),
('Ängelholm Golf Club', 'Ängelholm', '/placeholder.svg', 0, 0),
('Öijared Golf Club', 'Floda', '/placeholder.svg', 0, 0),
('Öland Golf Club', 'Borgholm', '/placeholder.svg', 0, 0),
('Åkersberga Golf Club', 'Åkersberga', '/placeholder.svg', 0, 0),
('Åstorp Golf Club', 'Åstorp', '/placeholder.svg', 0, 0);