// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fzhmvraztypgemyrguxw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ6aG12cmF6dHlwZ2VteXJndXh3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4MTg2MTgsImV4cCI6MjA2OTM5NDYxOH0.Tl--ysoIxUslKsX_9TOj6zdCx55O9LZHASKXHEo8iN4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    flowType: 'implicit',
  }
});